# Generated by Django 3.0.5 on 2020-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0009_auto_20200422_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
